package com.software.entity;

import java.io.Serializable;
import java.util.Date;

public class Attention implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column attention.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column attention.fan
     *
     * @mbggenerated
     */
    private String fan;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column attention.blogger
     *
     * @mbggenerated
     */
    private String blogger;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column attention.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column attention.modify_time
     *
     * @mbggenerated
     */
    private Date modifyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table attention
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column attention.id
     *
     * @return the value of attention.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column attention.id
     *
     * @param id the value for attention.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column attention.fan
     *
     * @return the value of attention.fan
     *
     * @mbggenerated
     */
    public String getFan() {
        return fan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column attention.fan
     *
     * @param fan the value for attention.fan
     *
     * @mbggenerated
     */
    public void setFan(String fan) {
        this.fan = fan == null ? null : fan.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column attention.blogger
     *
     * @return the value of attention.blogger
     *
     * @mbggenerated
     */
    public String getBlogger() {
        return blogger;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column attention.blogger
     *
     * @param blogger the value for attention.blogger
     *
     * @mbggenerated
     */
    public void setBlogger(String blogger) {
        this.blogger = blogger == null ? null : blogger.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column attention.create_time
     *
     * @return the value of attention.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column attention.create_time
     *
     * @param createTime the value for attention.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column attention.modify_time
     *
     * @return the value of attention.modify_time
     *
     * @mbggenerated
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column attention.modify_time
     *
     * @param modifyTime the value for attention.modify_time
     *
     * @mbggenerated
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attention
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", fan=").append(fan);
        sb.append(", blogger=").append(blogger);
        sb.append(", createTime=").append(createTime);
        sb.append(", modifyTime=").append(modifyTime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}