package com.software.entity;

import java.io.Serializable;
import java.util.Date;

public class Chatmessage implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chatmessage.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chatmessage.fromId
     *
     * @mbggenerated
     */
    private String fromid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chatmessage.toId
     *
     * @mbggenerated
     */
    private String toid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chatmessage.content
     *
     * @mbggenerated
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chatmessage.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chatmessage.modify_time
     *
     * @mbggenerated
     */
    private Date modifyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table chatmessage
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chatmessage.id
     *
     * @return the value of chatmessage.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chatmessage.id
     *
     * @param id the value for chatmessage.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chatmessage.fromId
     *
     * @return the value of chatmessage.fromId
     *
     * @mbggenerated
     */
    public String getFromid() {
        return fromid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chatmessage.fromId
     *
     * @param fromid the value for chatmessage.fromId
     *
     * @mbggenerated
     */
    public void setFromid(String fromid) {
        this.fromid = fromid == null ? null : fromid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chatmessage.toId
     *
     * @return the value of chatmessage.toId
     *
     * @mbggenerated
     */
    public String getToid() {
        return toid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chatmessage.toId
     *
     * @param toid the value for chatmessage.toId
     *
     * @mbggenerated
     */
    public void setToid(String toid) {
        this.toid = toid == null ? null : toid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chatmessage.content
     *
     * @return the value of chatmessage.content
     *
     * @mbggenerated
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chatmessage.content
     *
     * @param content the value for chatmessage.content
     *
     * @mbggenerated
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chatmessage.create_time
     *
     * @return the value of chatmessage.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chatmessage.create_time
     *
     * @param createTime the value for chatmessage.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chatmessage.modify_time
     *
     * @return the value of chatmessage.modify_time
     *
     * @mbggenerated
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chatmessage.modify_time
     *
     * @param modifyTime the value for chatmessage.modify_time
     *
     * @mbggenerated
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chatmessage
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", fromid=").append(fromid);
        sb.append(", toid=").append(toid);
        sb.append(", content=").append(content);
        sb.append(", createTime=").append(createTime);
        sb.append(", modifyTime=").append(modifyTime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}