package com.software.entity;

import java.io.Serializable;
import java.util.Date;

public class Friend implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column friend.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column friend.userid_first
     *
     * @mbggenerated
     */
    private String useridFirst;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column friend.userid_second
     *
     * @mbggenerated
     */
    private String useridSecond;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column friend.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column friend.modify_time
     *
     * @mbggenerated
     */
    private Date modifyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table friend
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column friend.id
     *
     * @return the value of friend.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column friend.id
     *
     * @param id the value for friend.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column friend.userid_first
     *
     * @return the value of friend.userid_first
     *
     * @mbggenerated
     */
    public String getUseridFirst() {
        return useridFirst;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column friend.userid_first
     *
     * @param useridFirst the value for friend.userid_first
     *
     * @mbggenerated
     */
    public void setUseridFirst(String useridFirst) {
        this.useridFirst = useridFirst == null ? null : useridFirst.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column friend.userid_second
     *
     * @return the value of friend.userid_second
     *
     * @mbggenerated
     */
    public String getUseridSecond() {
        return useridSecond;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column friend.userid_second
     *
     * @param useridSecond the value for friend.userid_second
     *
     * @mbggenerated
     */
    public void setUseridSecond(String useridSecond) {
        this.useridSecond = useridSecond == null ? null : useridSecond.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column friend.create_time
     *
     * @return the value of friend.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column friend.create_time
     *
     * @param createTime the value for friend.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column friend.modify_time
     *
     * @return the value of friend.modify_time
     *
     * @mbggenerated
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column friend.modify_time
     *
     * @param modifyTime the value for friend.modify_time
     *
     * @mbggenerated
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table friend
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", useridFirst=").append(useridFirst);
        sb.append(", useridSecond=").append(useridSecond);
        sb.append(", createTime=").append(createTime);
        sb.append(", modifyTime=").append(modifyTime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}