package com.software.entity;

import java.io.Serializable;
import java.util.Date;

public class Share implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column share.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column share.content
     *
     * @mbggenerated
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column share.image_url
     *
     * @mbggenerated
     */
    private String imageUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column share.yh_id
     *
     * @mbggenerated
     */
    private String yhId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column share.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column share.modify_time
     *
     * @mbggenerated
     */
    private Date modifyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column share.yh_name
     *
     * @mbggenerated
     */
    private String yhName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table share
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column share.id
     *
     * @return the value of share.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column share.id
     *
     * @param id the value for share.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column share.content
     *
     * @return the value of share.content
     *
     * @mbggenerated
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column share.content
     *
     * @param content the value for share.content
     *
     * @mbggenerated
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column share.image_url
     *
     * @return the value of share.image_url
     *
     * @mbggenerated
     */
    public String getImageUrl() {
        return imageUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column share.image_url
     *
     * @param imageUrl the value for share.image_url
     *
     * @mbggenerated
     */
    public void setImageUrl(String imageUrl) {
        this.imageUrl = imageUrl == null ? null : imageUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column share.yh_id
     *
     * @return the value of share.yh_id
     *
     * @mbggenerated
     */
    public String getYhId() {
        return yhId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column share.yh_id
     *
     * @param yhId the value for share.yh_id
     *
     * @mbggenerated
     */
    public void setYhId(String yhId) {
        this.yhId = yhId == null ? null : yhId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column share.create_time
     *
     * @return the value of share.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column share.create_time
     *
     * @param createTime the value for share.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column share.modify_time
     *
     * @return the value of share.modify_time
     *
     * @mbggenerated
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column share.modify_time
     *
     * @param modifyTime the value for share.modify_time
     *
     * @mbggenerated
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column share.yh_name
     *
     * @return the value of share.yh_name
     *
     * @mbggenerated
     */
    public String getYhName() {
        return yhName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column share.yh_name
     *
     * @param yhName the value for share.yh_name
     *
     * @mbggenerated
     */
    public void setYhName(String yhName) {
        this.yhName = yhName == null ? null : yhName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table share
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", content=").append(content);
        sb.append(", imageUrl=").append(imageUrl);
        sb.append(", yhId=").append(yhId);
        sb.append(", createTime=").append(createTime);
        sb.append(", modifyTime=").append(modifyTime);
        sb.append(", yhName=").append(yhName);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}