package com.software.entity;

import java.io.Serializable;
import java.util.Date;

public class Video implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video.content_url
     *
     * @mbggenerated
     */
    private String contentUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video.cover_url
     *
     * @mbggenerated
     */
    private String coverUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video.title
     *
     * @mbggenerated
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video.type
     *
     * @mbggenerated
     */
    private Integer type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video.source
     *
     * @mbggenerated
     */
    private String source;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video.des
     *
     * @mbggenerated
     */
    private String des;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video.modify_time
     *
     * @mbggenerated
     */
    private Date modifyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video.yh_id
     *
     * @mbggenerated
     */
    private String yhId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video.label
     *
     * @mbggenerated
     */
    private String label;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video.repos
     *
     * @mbggenerated
     */
    private String repos;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video.duration
     *
     * @mbggenerated
     */
    private Integer duration;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table video
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video.id
     *
     * @return the value of video.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video.id
     *
     * @param id the value for video.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video.content_url
     *
     * @return the value of video.content_url
     *
     * @mbggenerated
     */
    public String getContentUrl() {
        return contentUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video.content_url
     *
     * @param contentUrl the value for video.content_url
     *
     * @mbggenerated
     */
    public void setContentUrl(String contentUrl) {
        this.contentUrl = contentUrl == null ? null : contentUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video.cover_url
     *
     * @return the value of video.cover_url
     *
     * @mbggenerated
     */
    public String getCoverUrl() {
        return coverUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video.cover_url
     *
     * @param coverUrl the value for video.cover_url
     *
     * @mbggenerated
     */
    public void setCoverUrl(String coverUrl) {
        this.coverUrl = coverUrl == null ? null : coverUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video.title
     *
     * @return the value of video.title
     *
     * @mbggenerated
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video.title
     *
     * @param title the value for video.title
     *
     * @mbggenerated
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video.type
     *
     * @return the value of video.type
     *
     * @mbggenerated
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video.type
     *
     * @param type the value for video.type
     *
     * @mbggenerated
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video.source
     *
     * @return the value of video.source
     *
     * @mbggenerated
     */
    public String getSource() {
        return source;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video.source
     *
     * @param source the value for video.source
     *
     * @mbggenerated
     */
    public void setSource(String source) {
        this.source = source == null ? null : source.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video.des
     *
     * @return the value of video.des
     *
     * @mbggenerated
     */
    public String getDes() {
        return des;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video.des
     *
     * @param des the value for video.des
     *
     * @mbggenerated
     */
    public void setDes(String des) {
        this.des = des == null ? null : des.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video.create_time
     *
     * @return the value of video.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video.create_time
     *
     * @param createTime the value for video.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video.modify_time
     *
     * @return the value of video.modify_time
     *
     * @mbggenerated
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video.modify_time
     *
     * @param modifyTime the value for video.modify_time
     *
     * @mbggenerated
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video.yh_id
     *
     * @return the value of video.yh_id
     *
     * @mbggenerated
     */
    public String getYhId() {
        return yhId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video.yh_id
     *
     * @param yhId the value for video.yh_id
     *
     * @mbggenerated
     */
    public void setYhId(String yhId) {
        this.yhId = yhId == null ? null : yhId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video.label
     *
     * @return the value of video.label
     *
     * @mbggenerated
     */
    public String getLabel() {
        return label;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video.label
     *
     * @param label the value for video.label
     *
     * @mbggenerated
     */
    public void setLabel(String label) {
        this.label = label == null ? null : label.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video.repos
     *
     * @return the value of video.repos
     *
     * @mbggenerated
     */
    public String getRepos() {
        return repos;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video.repos
     *
     * @param repos the value for video.repos
     *
     * @mbggenerated
     */
    public void setRepos(String repos) {
        this.repos = repos == null ? null : repos.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video.duration
     *
     * @return the value of video.duration
     *
     * @mbggenerated
     */
    public Integer getDuration() {
        return duration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video.duration
     *
     * @param duration the value for video.duration
     *
     * @mbggenerated
     */
    public void setDuration(Integer duration) {
        this.duration = duration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", contentUrl=").append(contentUrl);
        sb.append(", coverUrl=").append(coverUrl);
        sb.append(", title=").append(title);
        sb.append(", type=").append(type);
        sb.append(", source=").append(source);
        sb.append(", des=").append(des);
        sb.append(", createTime=").append(createTime);
        sb.append(", modifyTime=").append(modifyTime);
        sb.append(", yhId=").append(yhId);
        sb.append(", label=").append(label);
        sb.append(", repos=").append(repos);
        sb.append(", duration=").append(duration);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}