package com.software.model;

import lombok.Data;

import java.io.Serializable;
import java.util.Date;

@Data
public class AttentionModel implements Serializable {

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column attention.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column attention.fan
     *
     * @mbggenerated
     */
    private String fan;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column attention.blogger
     *
     * @mbggenerated
     */
    private String blogger;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column attention.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column attention.modify_time
     *
     * @mbggenerated
     */
    private Date modifyTime;
}
