package com.software.model;

import lombok.Data;

import java.io.Serializable;
import java.util.Date;

@Data
public class LabelModel implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column label.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column label.level
     *
     * @mbggenerated
     */
    private Integer level;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column label.relate_id
     *
     * @mbggenerated
     */
    private Integer relateId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column label.label_name
     *
     * @mbggenerated
     */
    private String labelName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column label.label_desc
     *
     * @mbggenerated
     */
    private String labelDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column label.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column label.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;
}
