package com.software.model;

import com.software.entity.Share;
import lombok.Data;
import org.springframework.beans.BeanUtils;

import java.io.Serializable;
import java.util.Date;
@Data
public class ShareModel implements Serializable {

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column share.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column share.content
     *
     * @mbggenerated
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column share.image_url
     *
     * @mbggenerated
     */
    private String imageUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column share.yh_id
     *
     * @mbggenerated
     */
    private String yhId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column share.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column share.modify_time
     *
     * @mbggenerated
     */
    private Date modifyTime;


    private String yhName;

    public static Share convertToShare(ShareModel shareModel){
        if(shareModel==null){
            return null;
        }
        Share share=new Share();
        BeanUtils.copyProperties(shareModel,share);
        return share;
    }

    public static ShareModel convertToShareModel(Share share){
        if(share==null){
            return null;
        }
        ShareModel shareModel=new ShareModel();
        BeanUtils.copyProperties(share,shareModel);
        return shareModel;
    }
}
