package com.software.model;

import com.software.entity.Yh;
import lombok.Data;
import org.springframework.beans.BeanUtils;

import java.io.Serializable;

/**
 * Created by lr12 on 2018/12/18.
 */
@Data
public class YhModel implements Serializable {

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yh.userid
     *
     * @mbggenerated
     */
    private String userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yh.password
     *
     * @mbggenerated
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yh.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yh.desc
     *
     * @mbggenerated
     */
    private String desc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yh.phone
     *
     * @mbggenerated
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yh.school
     *
     * @mbggenerated
     */
    private String school;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yh.sex
     *
     * @mbggenerated
     */
    private Integer sex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yh.grade
     *
     * @mbggenerated
     */
    private String grade;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yh.class_no
     *
     * @mbggenerated
     */
    private Integer classNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yh.role
     *
     * @mbggenerated
     */
    private String role;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yh.label
     *
     * @mbggenerated
     */
    private String label;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yh.sign
     *
     * @mbggenerated
     */
    private String sign;


    public static YhModel convert(Yh yh){
          if(yh==null){
              return null;
          }
          YhModel yhModel=new YhModel();
          BeanUtils.copyProperties(yh,yhModel);
          return yhModel;
    }

    public static Yh convertToYh(YhModel yhModel){
        if(yhModel==null){
            return null;
        }
        Yh yh=new Yh();
        BeanUtils.copyProperties(yhModel,yh);
        return yh;
    }
}
