package com.software.mapper;

import com.software.entity.Chatmessage;
import com.software.entity.ChatmessageExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ChatmessageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chatmessage
     *
     * @mbggenerated
     */
    int countByExample(ChatmessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chatmessage
     *
     * @mbggenerated
     */
    int deleteByExample(ChatmessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chatmessage
     *
     * @mbggenerated
     */
    int insert(Chatmessage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chatmessage
     *
     * @mbggenerated
     */
    int insertSelective(Chatmessage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chatmessage
     *
     * @mbggenerated
     */
    List<Chatmessage> selectByExample(ChatmessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chatmessage
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Chatmessage record, @Param("example") ChatmessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chatmessage
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Chatmessage record, @Param("example") ChatmessageExample example);
}