package com.software.mapper;

import com.software.entity.LikeData;
import com.software.entity.LikeDataExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface LikeDataMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table like_data
     *
     * @mbggenerated
     */
    int countByExample(LikeDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table like_data
     *
     * @mbggenerated
     */
    int deleteByExample(LikeDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table like_data
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer likeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table like_data
     *
     * @mbggenerated
     */
    int insert(LikeData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table like_data
     *
     * @mbggenerated
     */
    int insertSelective(LikeData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table like_data
     *
     * @mbggenerated
     */
    List<LikeData> selectByExample(LikeDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table like_data
     *
     * @mbggenerated
     */
    LikeData selectByPrimaryKey(Integer likeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table like_data
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") LikeData record, @Param("example") LikeDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table like_data
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") LikeData record, @Param("example") LikeDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table like_data
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(LikeData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table like_data
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(LikeData record);
}